# configs/config.yaml
factors:
  - name: xy
    pre_lag: 6
    bar_lag: 5
    frequency: '4h'
    run_mode: 'online'
    start_date: '2024-01-01'
    end_date: '2025-01-01'
    # if_addition: true
    bar_fields:
      - 'Open'
      - 'Last'
    start_label: 0
    end_label: 288
    # composite_method: true
    # depend_factor_field:
    #   - 'xy'
    #   - 'xy1'
  # - name: xy3
  #   pre_lag: 6
  #   bar_lag: 5
  #   frequency: '4h'
  #   run_mode: 'all'
  #   start_date: '2024-01-01'
  #   end_date: '2025-01-01'
  #   if_addition: true
  #   bar_fields:
  #     - 'Open'
  #     - 'Last'
  #   composite_method: true
  #   depend_factor_field:
  #     - 'xy'
  #     - 'xy1'
