# configs/factor.yaml
factors:
  # - name: vpt
  #   pre_lag: 12 # 第一个数据点需要的时间长度, 默认为1000, 单位是frequency参数频率下的, bar数量，建议不要于bar_lag差距过大，会降低计算效率
  #   bar_lag: 12  # rolling时每一个数据点需要的时间长度
  #   frequency: '4h'  # '10m', '15m', '30m', '1h',  '4h', '6h', '8h', '1d'
  #   run_mode: 'all' # 'all', 'recent', 'online'
  #   start_date: '2025-01-01'  # 开始时间, 只对run_mode='all'有效
  #   end_date: '2025-05-13'    # 结束时间, 只对run_mode='all'有效
  #   # if_addition: true       # online模式下需要为true, 其他无所谓，填不填都行
  #   bar_fields: # 需要的原始数据的字段，首字母大写
  #     - 'Open'
  #     - 'Last'
  #     - 'Volume'
  #   start_label: 0  # start_date对应的label start_date + start_label = 因子的第一个数据点的时间，默认0
  #   end_label: 288  # end_date对应的label end_date + end_label = 因子的最后一个数据点的时间, 默认288
  #   # composite_method: true  # 是否需要依赖前置因子
  #   # depend_factor_field:     # 以来的前置因子的名称，使用时首先要确保前置因子已经计算完毕
  #   #   - 'xy'
  #   #   - 'xy1'
  #   factortype: 'pv'
  #   author: 'yzl' ## boxu, gt, yzl 必须按这样填写, 会去区分路径, 正确填写不然会报错
  #   if_prod: False  ## 是否上线
  #   level: 1  ## 层级，依赖原始数据的为1，依赖1级因子的为2，以此类推
  #   if_crontab: False  ## 是否配置cron定时任务
  #   out_sample_date: '2024-01-01'  ## out_sample的开始时间


  - name: xy5
    pre_lag: 6 # 第一个数据点需要的时间长度, 默认为1000, 单位是frequency参数频率下的, bar数量，建议不要于bar_lag差距过大，会降低计算效率
    bar_lag: 5  # rolling时每一个数据点需要的时间长度
    frequency: '8h'  # '10m', '15m', '30m', '1h',  '4h', '6h', '8h', '1d'
    run_mode: 'all' # 'all', 'recent', 'online'
    start_date: '2025-01-01'  # 开始时间, 只对run_mode='all'有效
    end_date: '2025-05-13'    # 结束时间, 只对run_mode='all'有效
    # if_addition: true       # online模式下需要为true, 其他无所谓，填不填都行
    bar_fields: # 需要的原始数据的字段，首字母大写
      - 'Open'
      - 'Last'
    start_label: 0  # start_date对应的label start_date + start_label = 因子的第一个数据点的时间，默认0
    end_label: 288  # end_date对应的label end_date + end_label = 因子的最后一个数据点的时间, 默认288
    # composite_method: true  # 是否需要依赖前置因子
    # depend_factor_field:     # 以来的前置因子的名称，使用时首先要确保前置因子已经计算完毕
    #   - 'xy'
    #   - 'xy1'
    factortype: 'pv'
    author: 'yzl' ## boxu, gt, yzl 必须按这样填写, 会去区分路径, 正确填写不然会报错
    if_prod: False  ## 是否上线
    level: 1  ## 层级，依赖原始数据的为1，依赖1级因子的为2，以此类推
    if_crontab: False  ## 是否配置cron定时任务
    out_sample_date: '2024-01-01'  ## out_sample的开始时间


#  - name: xy3
#    pre_lag: 6
#    bar_lag: 5
#    frequency: '4h'
#    run_mode: 'all'
#    start_date: '2024-01-01'
#    end_date: '2025-01-01'
#    if_addition: true
#    bar_fields:
#      - 'Open'
#      - 'Last'
#    composite_method: true
#    depend_factor_field:
#      - 'xy5'
#      # - 'xy1'
